### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mario-pz** [mario-pz/ansible_topics#1]
- [ ] Add role examples, both existing and custom ones
- [ ] add more best practices and principles
- [ ] add realistic exercises, and it should cover all playbook theory
